### ISSUE TITLE
TextInput, InputSection 리팩토링

### ISSUE THREAD

**Issue by NiNinanana** [jaemisam-a/dangol-sonnim-frontend#129]
## Description
TextInput과 InputSection의 리팩토링을 진행한다.
컴포넌트를 사용하기 편하게 주석과 사용하지 않는 것을 제거합니다.

## Todo
- [x] inputType에 Email, 전화번호 추가
- [x] input 입력 최대 개수 제한
- [x] InputSectionTypes export해서 사용
- [x] InputSectionTypes에 주석 추가
