### ISSUE TITLE
가게 정보 등록 페이지 마크업

### ISSUE THREAD

**Issue by mynameisjisoo** [jaemisam-a/dangol-sonnim-frontend#142]
## Description
* 가게 정보 등록 페이지 마크업을 진행한다.
<img width="272" alt="image" src="https://user-images.githubusercontent.com/84840032/224208037-d8699c8c-a832-4e8f-8fc3-6a4d1a18d93c.png">

## Todo
- [x] 섹션 컴포넌트 생성하여 스타일링 재사용
- [ ] 위치 필드에서 주소 검색 페이지로 연결
- [x] 서비스 태그 컴포넌트 구현
