### ISSUE TITLE
사이드 navbar 구현

### ISSUE THREAD

**Issue by mynameisjisoo** [jaemisam-a/dangol-sonnim-frontend#143]
## Description
* 사장님 페이지의 사이드 navbar의 레이아웃과 내부에 들어가는 내용을 구현한다.
## Todo
- [ ] 사이드 네비바 레이아웃을 공통 컴포넌트로 구현한다.
- [ ] 가게 설정 페이지에서 햄버거 버튼 클릭 시 사이드 네비바가 나온다.
- [ ] 네비바에서 계정 이메일 클릭 시 계정 정보 페이지 연결된다.
