### ISSUE TITLE
사장님 회원가입 API 연결

### ISSUE THREAD

**Issue by NiNinanana** [jaemisam-a/dangol-sonnim-frontend#198]
## Description
사장님 회원가입 API를 연결해야 한다.
페이지 이동할 때마다 데이터를 갖고 가야하며, 없이 페이지를 들어왔을 때에는 로그인 페이지로 보내야 한다.

## Todo
- [x] 회원가입 중 페이지 이동 시 데이터 이동
- [x] 이메일 인증 API 연결
- [x] 회원가입 API 연결
