### ISSUE TITLE
사장님 로그인 API 연결

### ISSUE THREAD

**Issue by NiNinanana** [jaemisam-a/dangol-sonnim-frontend#212]
## Description
사장님 로그인 API를 연결해야 한다. 로그인 후 로그아웃도 가능해야하며 상태 관리도 되어야 한다.

## Todo
- [x] 로그인 API 연결
- [x] 로그인 상태 관리
- [x] 로그아웃 기능 추가
