### ISSUE TITLE
주소검색페이지 내 체크버튼 구현

### ISSUE THREAD

**Issue by mynameisjisoo** [jaemisam-a/dangol-sonnim-frontend#222]
## Description
* 사장님 페이지 헤더의 체크버튼 클릭 시 수행할 동작을 정의해야 한다.
* 주소검색페이지에서 주소 선택 후 체크버튼 클릭 시 선택한 주소값을 원하는 페이지에서 쓸 수 있어야 한다.
## Todo
- [x] 헤더 체크버튼 수정
- [x] 가게등록페이지의 주소 필드 선택 시 주소 검색 페이지로 연결
- [x] 가게등록페이지로 선택한 주소 값 가져오기
