### ISSUE TITLE
사장님 마이페이지, 탈퇴 구현

### ISSUE THREAD

**Issue by mynameisjisoo** [jaemisam-a/dangol-sonnim-frontend#270]
## Description
사장님 마이페이지, 내 정보 페이지 구현

## Todo
- [x] 사업자 등록번호 UI 제거
- [x] 회원 탈퇴 api 연결
- [x] 사이드 네비바에 로그인한 이메일 보여주기
