### ISSUE TITLE
구독권 API 관련 수정

### ISSUE THREAD

**Issue by mynameisjisoo** [jaemisam-a/dangol-sonnim-frontend#272]
## Description
* 구독권 API querykey 수정

## Todo
- [x] 구독권관련 API querykey 수정
- [x] 구독권 생성 api 연결
- [x] popover에서 구독권 수정 UI 제거
